-- Khmer Architecture Archive — seed the `entries` table
-- Sprint 2, Lab 6, Part 2. Run in the Supabase SQL Editor AFTER entries.sql.
--
-- BEFORE RUNNING: replace every PASTE-YOUR-UUID-HERE with your own user id.
--   Dashboard → Authentication → Users → click yourself → copy the UUID.
-- Find/replace all occurrences (there are 7, one per row).
--
-- Khmer text is copied verbatim from data/entries.js. Photo paths are
-- copied exactly as they appear in the repo (e.g. /IFL_1.JPG) and remote
-- Unsplash URLs are left unchanged. id/created_at come from the column
-- defaults, so they are not listed here. Newest-first ordering later comes
-- from created_at, so these insert top-to-bottom in the data file's order.

insert into entries
  (owner, title_en, title_km, era_en, era_km, location_en, location_km,
   year_en, year_km, description_en, description_km, story_en, story_km,
   contributor_en, contributor_km, places_en, places_km, image_url, action_href)
values
  ('PASTE-YOUR-UUID-HERE',
   'Institute of Foreign Languages (IFL)',
   'វិទ្យាស្ថានភាសាបរទេស (IFL)',
   'New Khmer',
   'សម័យខ្មែរថ្មី',
   'Phnom Penh',
   'រាជធានីភ្នំពេញ',
   '1972',
   'គ.ស. ១៩៧២',
   'Originally designed as the Teacher Training College on Russian Boulevard, internationally hailed as one of the finest modernist educational campuses in Asia.',
   'ដើមឡើយត្រូវបានរចនាឡើងជាមហាវិទ្យាល័យគរុកោសល្យជាន់ខ្ពស់នៅលើមហាវិថីសហព័ន្ធរុស្ស៊ី ដែលត្រូវបានអន្តរជាតិចាត់ទុកថាជាបរិវេណអប់រំបែបទំនើបនិយមដ៏ល្អឯកបំផុតមួយនៅអាស៊ី។',
   'Conceived as an inhabited modern castle referencing Angkor Wat''s causeways. Elevated bridge walkways lead across rainwater retention ponds into classroom pavilions shielded by geometric concrete brise-soleil lattice work that diffuses midday tropical glare.',
   'ត្រូវបានបង្កើតឡើងជាបន្ទាយប្រាសាទទំនើប ដោយយកលំនាំតាមស្ពានហាលនៃប្រាសាទអង្គរវត្ត។ ស្ពានដើរលើអាកាសឆ្លងកាត់ស្រះទឹកឈូកស្តុកទឹកភ្លៀង ឆ្ពោះទៅកាន់អគារសិក្សាដែលការពារដោយបន្ទះក្បាច់បេតុងការពារកម្ដៅថ្ងៃ (Brise-soleil) ជួយសម្រាលពន្លឺថ្ងៃត្រង់ដ៏ក្តៅនៃតំបន់ត្រូពិច។',
   'Royal University of Phnom Penh (RUPP)',
   'សាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ (RUPP)',
   array['Elevated Walkway Bridge', 'Lotus Ponds', 'Lecture Amphitheater', 'Brise-Soleil Facades'],
   array['ស្ពានដើរលើអាកាស', 'ស្រះឈូក', 'សាលបង្រៀនថ្នាក់កាំជណ្តើរ', 'ក្បាច់បេតុងការពារកម្ដៅ'],
   '/IFL_1.JPG',
   '/archive/ifl'),

  ('PASTE-YOUR-UUID-HERE',
   'Institute for International Studies and Public Policy (IISPP)',
   'វិទ្យាស្ថានសិក្សាអន្តរជាតិ និងគោលនយោបាយសាធារណៈ (IISPP)',
   'New Khmer / Contemporary',
   'សម័យខ្មែរថ្មី / សហសម័យ',
   'Phnom Penh',
   'រាជធានីភ្នំពេញ',
   '1972 / Modern',
   '១៩៧២ / ទំនើប',
   'A flagship academic institute situated at the Royal University of Phnom Penh campus, advancing diplomatic studies, international relations, and public administration.',
   'វិទ្យាស្ថានសិក្សាជាន់ខ្ពស់ឈានមុខគេដែលស្ថិតនៅក្នុងបរិវេណសាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ ក្នុងការបណ្តុះបណ្តាលទំនាក់ទំនងអន្តរជាតិ ការទូត និងគោលនយោបាយសាធារណៈ។',
   'Integrated seamlessly within the modernist educational complex on Russian Boulevard, featuring climate-adapted structural layouts, cantilevered corridors, and expansive green courtyards that facilitate scholarly dialogue.',
   'ត្រូវបានរួមបញ្ចូលយ៉ាងចុះសម្រុងគ្នាក្នុងបរិវេណអប់រំទំនើបកម្មលើមហាវិថីសហព័ន្ធរុស្ស៊ី ដោយមានរចនាសម្ព័ន្ធសម្របតាមអាកាសធាតុ របៀងធំទូលាយ និងទីធ្លាបៃតងសម្រាប់កិច្ចសន្ទនាស្រាវជ្រាវ។',
   'Royal University of Phnom Penh (RUPP) · IISPP',
   'សាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ (RUPP) · IISPP',
   array['Academic Hall', 'Conference Wings', 'Research Center', 'Campus Courtyard'],
   array['សាលសិក្សា', 'អគារសន្និសីទ', 'មជ្ឈមណ្ឌលស្រាវជ្រាវ', 'ទីធ្លាបរិវេណ'],
   '/ISPP_main.JPG',
   '/archive/iispp'),

  ('PASTE-YOUR-UUID-HERE',
   'Department of French',
   'ដេប៉ាតឺម៉ង់ភាសាបារាំង',
   'New Khmer',
   'សម័យខ្មែរថ្មី',
   'Phnom Penh',
   'រាជធានីភ្នំពេញ',
   '1972',
   'គ.ស. ១៩៧២',
   'A distinguished language department pavilion nestled within the Institute of Foreign Languages campus, fostering Franco-Khmer educational and cultural exchange.',
   'អគារដេប៉ាតឺម៉ង់ភាសាដ៏លេចធ្លោមួយស្ថិតនៅក្នុងបរិវេណវិទ្យាស្ថានភាសាបរទេស ដែលលើកកម្ពស់ការផ្លាស់ប្តូរការអប់រំ និងវប្បធម៌បារាំង-ខ្មែរ។',
   'Sculpted with distinctive modernist concrete brise-soleil sunshades, sheltered outdoor corridors, and tropical cross-ventilation principles conceived by Vann Molyvann.',
   'រចនាឡើងជាមួយនឹងបន្ទះក្បាច់បេតុងការពារកម្ដៅថ្ងៃ (Brise-soleil) របៀងខាងក្រៅមានម្លប់ និងគោលការណ៍បញ្ចេញបញ្ចូលខ្យល់ធម្មជាតិតាមបែបត្រូពិចដែលបង្កើតឡើងដោយលោក វណ្ណ ម៉ូលីវណ្ណ។',
   'Institute of Foreign Languages (IFL) · RUPP',
   'វិទ្យាស្ថានភាសាបរទេស (IFL) · RUPP',
   array['French Language Pavilion', 'Shaded Balconies', 'Reading Courtyard'],
   array['អគារភាសាបារាំង', 'យ៉រមានម្លប់', 'ទីធ្លាអានសៀវភៅ'],
   '/France_main.JPG',
   '/archive/french'),

  ('38bd1090-9bd0-43f0-8de8-bca9a5ce9470',
   'Independence Monument',
   'វិមានឯករាជ្យ',
   'New Khmer',
   'សម័យខ្មែរថ្មី',
   'Phnom Penh',
   'រាជធានីភ្នំពេញ',
   '1958',
   'គ.ស. ១៩៥៨',
   'Designed by revered Cambodian architect Vann Molyvann to commemorate Cambodia''s liberation from French colonial protectorate rule in 1953.',
   'រចនាឡើងដោយស្ថាបត្យករខ្មែរដ៏ល្បីល្បាញ លោក វណ្ណ ម៉ូលីវណ្ណ ដើម្បីរំឭកដល់ការទទួលបានឯករាជ្យពេញលេញរបស់កម្ពុជាពីអាណាព្យាបាលបារាំងនៅឆ្នាំ១៩៥៣។',
   'Shaped as an elegant multi-tiered blossoming lotus stupa inspired by the classical Angkorian central towers of Banteay Srei, cast in reinforced modern red ochre concrete. Its 100 serpent-headed Naga tiers signify sovereign rebirth.',
   'មានរាងជាចេតិយផ្កាឈូកក្រពុំថ្នាក់ៗដ៏ស្រស់ស្អាត ដែលទទួលបានការបំផុសគំនិតពីប្រាង្គកណ្តាលនៃប្រាសាទបន្ទាយស្រី សាងសង់ពីបេតុងពង្រឹងទំនើបពណ៌ក្រហមដីឥដ្ឋ។ ក្បាលនាគចំនួន ១០០ នៅតាមថ្នាក់តំណាងឱ្យការរស់ឡើងវិញនៃអធិបតេយ្យភាពជាតិ។',
   'Vann Molyvann Project · Phnom Penh Capital Hall',
   'គម្រោង វណ្ណ ម៉ូលីវណ្ណ · សាលារាជធានីភ្នំពេញ',
   array['Norodom & Sihanouk Boulevard Intersection', 'Suramarit Park'],
   array['ប្រសព្វមហាវិថីនរោត្តម និងសីហនុ', 'សួនច្បារសុរាម្រឹត'],
   'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
   '/archive/3'),

  ('38bd1090-9bd0-43f0-8de8-bca9a5ce9470',
   'Olympic Stadium Complex',
   'ពហុកីឡដ្ឋានជាតិអូឡាំពិក',
   'New Khmer',
   'សម័យខ្មែរថ្មី',
   'Phnom Penh',
   'រាជធានីភ្នំពេញ',
   '1964',
   'គ.ស. ១៩៦៤',
   'Vann Molyvann''s engineering marvel — a 70,000-seat multi-sport colosseum designed for the 1963 Southeast Asian Peninsular Games.',
   'ស្នាដៃវិស្វកម្មដ៏អស្ចារ្យរបស់លោក វណ្ណ ម៉ូលីវណ្ណ — ជាកីឡដ្ឋានដែលអាចផ្ទុកទស្សនិកជនបានរហូតដល់ ៧០,០០០ នាក់ សាងសង់ឡើងសម្រាប់ការប្រកួតកីឡាអាស៊ីអាគ្នេយ៍ឆ្នាំ១៩៦៣។',
   'A masterpiece of climate-responsive architecture utilizing colossal earth dikes excavated from surrounding stormwater treatment moats. The indoor arena features cantilevered prestressed concrete umbrellas that channel cross-draft breezes without mechanical air-conditioning.',
   'ជាស្នាដៃឯកនៃស្ថាបត្យកម្មឆ្លើយតបនឹងអាកាសធាតុ ដោយប្រើប្រាស់ទំនប់ដីដ៏ធំដែលជីកចេញពីអាងស្តុកទឹកភ្លៀងព័ទ្ធជុំវិញ។ សាលកីឡាក្នុងផ្ទះមានដំបូលបេតុងរាងឆត្របញ្ឈរដែលអាចនាំខ្យល់ត្រជាក់បក់កាត់ដោយធម្មជាតិ ដោយមិនចាំបាច់ប្រើម៉ាស៊ីនត្រជាក់ឡើយ។',
   'Ministry of Education, Youth and Sport · Vann Molyvann Archive',
   'ក្រសួងអប់រំ យុវជន និងកីឡា · បណ្ណសារ វណ្ណ ម៉ូលីវណ្ណ',
   array['Indoor Sports Arena', 'Aquatic Diving Complex', 'Moat Catchment Reservoirs'],
   array['សាលកីឡាក្នុងផ្ទះ', 'អាងហែលទឹក និងលោតទឹក', 'អាងស្តុកទឹកភ្លៀង'],
   'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
   '/archive/5'),

  ('38bd1090-9bd0-43f0-8de8-bca9a5ce9470',
   'Chaktomuk Conference Hall',
   'សាលសន្និបាតចតុមុខ',
   'New Khmer',
   'សម័យខ្មែរថ្មី',
   'Phnom Penh',
   'រាជធានីភ្នំពេញ',
   '1961',
   'គ.ស. ១៩៦១',
   'A landmark triangular auditorium situated right at the confluence of the Tonle Sap, Bassac, and Mekong rivers.',
   'សាលមហោស្រពរាងត្រីកោណដ៏លេចធ្លោ ដែលស្ថិតនៅចំកន្លែងប្រសព្វនៃទន្លេសាប ទន្លេបាសាក់ និងទន្លេមេគង្គ (ទន្លេចតុមុខ)។',
   'Designed by Vann Molyvann taking inspiration from an unfurling palm-leaf fan. The folding concrete roof structure acts as both acoustic dampening ceiling and natural ventilation flutes, pointing dramatically towards the four water branches (Chaktomuk).',
   'រចនាឡើងដោយលោក វណ្ណ ម៉ូលីវណ្ណ ដោយយកលំនាំតាមផ្លិតស្លឹកត្នោតដែលបើកលាតសន្ធឹង។ រចនាសម្ព័ន្ធដំបូលបេតុងបត់ជួយទប់សូរសំឡេង និងជាបំពង់បង្ហូរខ្យល់ធម្មជាតិយ៉ាងមានប្រសិទ្ធភាព ដោយបែរមុខយ៉ាងស្រស់ស្អាតទៅកាន់ទន្លេទាំងបួន។',
   'Ministry of Culture and Fine Arts',
   'ក្រសួងវប្បធម៌ និងវិចិត្រសិល្បៈ',
   array['Sisowath Quay', 'Four Rivers Riverfront Confluence'],
   array['វិថីព្រះស៊ីសុវត្ថិ', 'ចំណុចប្រសព្វទន្លេចតុមុខ'],
   'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
   '/archive/6'),

  ('PASTE-YOUR-UUID-HERE',
   'Royal University of Fine Arts (RUFA)',
   'សាកលវិទ្យាល័យភូមិន្ទវិចិត្រសិល្បៈ',
   'New Khmer',
   'សម័យខ្មែរថ្មី',
   'Phnom Penh',
   'រាជធានីភ្នំពេញ',
   '1965',
   'គ.ស. ១៩៦៥',
   'The premier national arts and architecture academy established behind the National Museum to cultivate Cambodia''s architects, painters, and sculptors.',
   'គ្រឹះស្ថានឧត្តមសិក្សាសិល្បៈ និងស្ថាបត្យកម្មជាតិដំបូងគេ ដែលបង្កើតឡើងនៅខាងក្រោយសារមន្ទីរជាតិ ដើម្បីបណ្តុះបណ្តាលស្ថាបត្យករ វិចិត្រករ និងជាងចម្លាក់កម្ពុជា។',
   'Vann Molyvann served as RUFA''s first Dean of Architecture. He established a curriculum grounded in tropical environmental design, traditional wood joining techniques, and modular concrete construction so graduates could shape their nation''s contemporary identity.',
   'លោក វណ្ណ ម៉ូលីវណ្ណ បានកាន់តំណែងជាព្រឹទ្ធបុរសដំបូងនៃមហាវិទ្យាល័យស្ថាបត្យកម្ម។ លោកបានបង្កើតកម្មវិធីសិក្សាផ្អែកលើការរចនាស្របតាមអាកាសធាតុត្រូពិច វិធីតំណឈើបុរាណ និងការសាងសង់បេតុងទំនើប ដើម្បីឱ្យនិស្សិតអាចរួមចំណែកកសាងអត្តសញ្ញាណជាតិសហសម័យ។',
   'RUFA Faculty of Architecture · Lim Houykea',
   'មហាវិទ្យាល័យស្ថាបត្យកម្ម RUFA · លឹម ហ៊ុយគា',
   array['Faculty of Architecture Courtyard', 'Street 178 Heritage Corridor'],
   array['ទីធ្លាមហាវិទ្យាល័យស្ថាបត្យកម្ម', 'របៀងបេតិកភណ្ឌផ្លូវ ១៧៨'],
   'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&q=80',
   '/archive/7');
